# Generated by Django 4.2.27 on 2025-12-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_conversation_options_alter_conversation_state'),
        ('chat_messages', '0002_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('created_at',), 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation', verbose_name='Conversa'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='direction',
            field=models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received')], max_length=8, verbose_name='Direção'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário'),
        ),
    ]
