# Generated by Django 4.2.27 on 2025-12-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('created_at',), 'verbose_name': 'Conversa', 'verbose_name_plural': 'Conversas'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6, verbose_name='Estado'),
        ),
    ]
